[envs.default]
dependencies = [
    "coverage[toml]",
    "pytest"
]
[envs.default.scripts]
test = "pytest {args:tests}"
test-cov = "coverage run -m pytest {args:tests}"
cov-report = [
    "- coverage combine",
    "coverage report --show-missing",
]
cov = [
    "test-cov",
    "cov-report",
]

[envs.all]
type = "container"

[[envs.all.matrix]]
python = ["3.9", "3.10", "3.11"]

[envs.lint]
detached = true
dependencies = [
    "black",
    "mypy",
    "pydantic",
    "pytest",
    "ruff",
]
[envs.lint.scripts]
typing = "mypy --install-types --non-interactive {args:src tests}"
style = [
    "ruff {args:.}",
    "black --check --diff {args:.}",
]
fmt = [
    "black {args:.}",
    "ruff --fix {args:.}",
    "style",
]
all = [
    "style",
    "typing",
]